version: '3'
services: 
  container_a:
    container_name: container_a
    build: ./confile/container_A
    ports: 
      - "8080"
    links: 
      - container_b 
    volumes: 
      - ./ping_res:/work_space/res.txt
  container_b: 
    container_name: container_b
    build: ./confile/container_B
    ports: 
      - "8080" 
    volumes: 
      - ./ping_res:/work_space/res.txt
