FROM nginx:latest

WORKDIR /work_space

COPY . .

# RUN cat sources_list.txt > /etc/apt/sources.list &&\
RUN sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list &&\
    sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list &&\
    apt-get -y update &&\ 
    apt-get -y upgrade &&\ 
    apt-get -y install inetutils-ping &&\ 
    apt-get -y clean &&\
    echo "finished RUN\n\n"

ENTRYPOINT ping container_a:8080 -c 10 >> ./res.txt && cat ./res.txt

CMD ping container_a:8080 -c 10 >> ./res.txt && cat ./res.txt && echo "finished code"
